name: store .serverless to s3

on:
  push:
    branches:
      - master

jobs:
  serverless-deploy:
    runs-on: ubuntu-18.04

    env:
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "14.x"

      - name: Install dependencies
        run: npm ci

      - name: Download `.serverless` state from S3
        run: aws s3 sync s3://${{secrets.SERVERLESS_BUCKET}}/.serverless .serverless --delete

      - name: Deploy Using serverless
        run: npx serverless

      - name: Upload `.serverless` state to S3
        run: aws s3 sync .serverless s3://${{secrets.SERVERLESS_BUCKET}}/.serverless --delete
